# Site
title: netgems
tagline: Notes and thoughts about network technologies and solutions.
description: >-
  netgems — notes and thoughts about network technologies and solutions
  by Alejandro Marin.
url: "https://amarinjs.github.io"
baseurl: "/sitio"
lang: en
timezone: Europe/London

# Author
author:
  name: Alejandro Marin
  bio: Notes and thoughts about network technologies and solutions.
  email: # add if you want it public
  github: alexma2344
  linkedin: alejandro-marin-768833117
  stackoverflow: "9938491"
  rss: "/feed.xml"

# Build
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
timezone: Europe/London

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: false

# Collections / defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Pagination
paginate: 10
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# SEO
twitter:
  card: summary
social:
  name: Alejandro Marin
  links:
    - https://github.com/alexma2344
    - https://www.linkedin.com/in/alejandro-marin-768833117
