# Site Settings
url: https://alexma2344.github.io
baseurl: /sitio
text_skin: forest
title: Netgems
description: >-
  Network Engineer & IT Infrastructure Specialist.
  Notes, guides, and reference material on networking, security, and systems administration.

# Language & Timezone
lang: en
timezone: Europe/London

# Author
author:
  name: Alejandro Marin
  bio: Network Engineer & IT Infrastructure Specialist
  linkedin: alejandro-marin-768833117
  github: alexma2344
  stackoverflow: 9938491

# Repository
repository: alexma2344/sitio
repository_tree: master

# Post
excerpt_separator: <!--more-->
permalink: date

# Pagination
paginate: 8
paginate_path: /page:num

# Markdown
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Analytics
google_analytics: "UA-146487120-1"

# Build
exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
